### ISSUE TITLE
Extract by expression

### ISSUE THREAD

**Issue by melwey** [BIOPAMA/protection_analyst#3]
typo in expression.
\"STATUS\"  = \'Eestablished\' should be \"STATUS\"  = \'Established\'

**Comment by lucageo** [comment]
Thanks a lot @melwey !

**Comment by melwey** [comment]
Missing step extract by expression on points?

**Comment by lucageo** [comment]
protectedplanet filtering procedure is:

Sites with *Status* = *Proposed, Not Reported*; *points with no reported
area*, and UNESCO Man and Biosphere Reserves are excluded.

So I'm not sure we do need to filter out points by expression...

Thanks
Luca

Il giorno lun 3 mag 2021 alle ore 13:26 melwey ***@***.***>
ha scritto:

**Comment by melwey** [comment]
Ciao Luca,

I think we should filter points because there are sites recorded as points
with ("STATUS" = 'Proposed' OR "STATUS" = 'Not Reported') AND "REP_AREA" >
0.

Also I do not see where you filter out sites that are 'DESIG_ENG" =
'UNESCO-MAB Biosphere Reserve'... You should add it to the
extractByExpression

> (all your previous conditions) AND NOT("DESIG_ENG" = 'UNESCO-MAB Biosphere
> Reserve')


Cheers
Mélanie
--
Mélanie Weynants

**Comment by lucageo** [comment]
Sounds good! Thanks Melanie!

Cheers
Luca

Il giorno lun 3 mag 2021 alle 18:21 melwey ***@***.***> ha
scritto:

**Comment by lucageo** [comment]
Done and thanks Melanie!

Il giorno lun 3 mag 2021 alle ore 18:21 melwey ***@***.***>
ha scritto:
